# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Daily Koszalin' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 pod 'FeedKit'
  # Pods for Daily Koszalin

  target 'Daily KoszalinTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Daily KoszalinUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
